apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-deployment
        image: pavansa/django-app-hello-world:latest
        ports:
        - containerPort: 8000
      restartPolicy: Always